name = "vaguely"
main = "worker.js"
compatibility_date = "2024-01-01"

[build]
command = ""
cwd = "."

[[routes]]
pattern = "vaguely.drewr.dev"
custom_domain = true

[env.production]
route = "https://vaguely.drewr.dev/*"
zone_name = "drewr.dev"
